### ISSUE TITLE
PHP in the instructions?  I thought the only server side technology was node.js.

### ISSUE THREAD

**Issue by 33bulldogs** [sumanpoluri/canvas-starter-kit#1]
First, thanks for providing what you've provided.  I started following your starter kit instructions because under the Hosted App section it says the only server technology needed is node.js express.  However in your instruction, now I see references to PHP:

9) Add App Consumer Data to PHP Pages

10) In the Hosted app find the canvas.php and the consumerData.js files.

Where are these PHP files and why are we using PHP here?  I'm confused by your statement of only using node.js express, yet on the other hand the instructions say to use these PHP files.

Am I just missing something about all this?  Sorry, I am a rookie at this Canvas app and Salesforce stuff...  

Thanks!
Nick

**Comment by sumanpoluri** [comment]
@webhelio, thank you for pointing out those `PHP` references. Thankfully, they're just a problem with the documentation in the `README` file. The [original version](https://github.com/seedcode/canvas-starter-kit) that I based this project off of was done in PHP, so that's where these references came from. I forgot to change a few of those in the README file. I fixed the points 9-13 now (changed `PHP` to `JS`).

Also, one word of caution. I haven't worked on this project in the last 2 years. So, please refer to Salesforce documentation for any changes to these APIs or product deprecations/enhancements since that time.
